name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1"


jobs:
  testing:
    runs-on: ubuntu-20.04

    steps:
      - name: Greetings from Github Actions
        shell: python
        run: |
          print("Hello World")

      - name: Checking out the repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Installing Python package and testing requirements
        run: |
          python -m pip install .
          python -m pip install -r requirements-dev.txt

      - name: Run Python tests
        run: pytest
