name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1"


jobs:
  testing:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - windows-2022
          - macos-11

    runs-on: ${{ matrix.os }}

    steps:
      - name: Greetings from the PowerShell
        if: runner.os == 'Windows'
        shell: powershell
        run: Write-Host "Windows PowerShell here"

      - name: Checking out the repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Installing Python package and testing requirements
        run: |
          python -m pip install .
          python -m pip install -r requirements-dev.txt

      - name: Run Python tests
        run: pytest
